### ISSUE TITLE
Update to psr/log 1.1.0

### ISSUE THREAD

**Issue by antonmarin** [samdark/yii2-psr-log-target#10]
Are you going to update to psr/log:1.1.0 ?

**Comment by samdark** [comment]
Maybe. Wasn't aware it was changed.

**Comment by samdark** [comment]
What's the difference?

**Comment by antonmarin** [comment]
https://github.com/Seldaek/monolog/pull/1229
https://github.com/php-fig/log/pull/57/files

Added test logger. I mean currently package requires ~1.0.2 so user can't require psr/log:^1.0

**Comment by samdark** [comment]
https://github.com/samdark/yii2-psr-log-target/releases/tag/1.0.7

**Comment by antonmarin** [comment]
Thanks
