### ISSUE TITLE
Context message get lost

### ISSUE THREAD

**Issue by rodion-k** [samdark/yii2-psr-log-target#13]
With the following config:
```php
[
    'class' => \samdark\log\PsrTarget::class,
    'logger' => $psrLogger,
    'levels' => ['error', 'warning'],
]
```
I want to receive only errors and warnings, but also context message, as I receive to email (\yii\log\EmailTarget) with same config.
Now errors and warnings are sent to prsLogger, but context message filtered by the [following line](https://github.com/samdark/yii2-psr-log-target/blob/47a55933a8c8035fd3c023d55c4be7427eefbd1c/src/PsrTarget.php#L70):
```php
if (!isset($this->_levels[$level])) {
    continue;
}
```
because it has info level

**Comment by samdark** [comment]
OK. Want to do a pull request?

**Comment by rodion-k** [comment]
Yes, I will try
