### ISSUE TITLE
Logging with yii3 psr-3 logger

### ISSUE THREAD

**Issue by TonisOrmisson** [samdark/yii2-psr-log-target#42]
I tested having yii3 [PSR-3 Logger](https://github.com/yiisoft/log/) with [FileTarget](https://github.com/yiisoft/log-target-file) with this package and the log is not written to file unless I change the flushInterval <= to actual messages on both Logger & Target.

### What steps will reproduce the problem?

1. install a clean yii2-basic-app
2. install related dependencies, this package, yii3 Logger & File target, also Monolog for comparison
3. configure logging to use this package with Monologue like: 
```
$monologPsrLogger = new \Monolog\Logger('my_logger');
$monologHandler = new \Monolog\Handler\StreamHandler($logFileName, Level::Info);
$monologPsrLogger->pushHandler($monologHandler);
//...//
$config = [
     // ...
    'components' => [
         //...
        'log' => [
            'targets' => [
                [
                    'class' => \samdark\log\PsrTarget::class,
                    'logger' => $monologPsrLogger,

                ],
                // ...
            ],
        ],

```
4. Check that logging works with Monolog PST target
5. Change the logger to yii3 logger
```
$fileTarget = new \Yiisoft\Log\Target\File\FileTarget($logFileName);
$yii3Logger = new \Yiisoft\Log\Logger([$fileTarget]);

//...//
$config = [
     // ...
    'components' => [
         //...
        'log' => [
            'targets' => [
                [
                    'class' => \samdark\log\PsrTarget::class,
                    'logger' => $yii3Logger,

                ],
                // ...
            ],
        ],

```

### What is the expected result?

Log is written to log file similarly as Monolog

### What do you get instead?
Nothing written to file

### Additional info

works if $flushInterval is set to match or < actual messages count eg; 
```
$fileTarget->setExportInterval(1);
$yii3Logger->setFlushInterval(1);
```

**Comment by samdark** [comment]
Messages are collected in memory and then flushed either when `flushInterval` is reached or when `flush()` is called.

Normally, it should be:

> Note: All message flushing and exporting also occurs when the application ends.

But, Yii3 events aren't automatically registered with Yii2 so `flush()` isn't called: 

https://github.com/yiisoft/log/blob/master/config/events-web.php#L13

**Comment by TonisOrmisson** [comment]
Thanks for replying. 

I'm not sure I understand what this means :) Is this a bug of this package or yii3 logger? I am assuming it still is a bug somewhere since it all should be PSR-3 compatible?

**Comment by samdark** [comment]
It is not a bug. You have to `flush()` the Yii3 target on https://www.yiiframework.com/doc/api/2.0/yii-base-application#EVENT_AFTER_REQUEST-detail or similar event.

**Comment by TonisOrmisson** [comment]
Thanks for the effort! Nevertheless I fail to get the result with adding an AppBootstrap and doing a flush() via the suggested event like that :

```
    public function bootstrap($app)
    {
        \yii\base\Event::on(\yii\base\Application::class, \yii\base\Application::EVENT_AFTER_REQUEST, function () {
            flush();
        });
    }
```
I was just testing how easy one could replace the yii2 logger with yii3 components.

**Comment by TonisOrmisson** [comment]
Thanks! Seems to work fine after attaching the event for example to bootstrap: 

```
    public function bootstrap($app)
    {
        \yii\base\Event::on(\yii\base\Application::class, \yii\base\Application::EVENT_AFTER_REQUEST, function () {
            \Yii::$app->log->logger->flush(true);
        });

    }
```
